name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps: 
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: sudo docker build -t poc-ci:latest .

  deploy:
    runs-on: self-hosted
    need: build
    env:
        CR_PAT: ${{ secrets.CR_PAT }}
    steps:
      - name: Print the PAT
        run: echo $CR_PAT
      - name: Login on Container registry
        run: echo $CR_PAT | sudo docker login ghcr.io -u dc-communication --password-stdin
      - name: Tag the image 
        run: sudo docker tag poc-ci ghcr.io/dc-communication/PoC-CI/poc-ci:latest
      - name: Push the image
        run: sudo docker push ghcr.io/dc-communication/PoC-CI/poc-ci:latest

